export type TProfile = {
  id: number;
  chat_id: number;
  created_by: number;
  updated_by: number;
  company_id: number;
  department_id: number;
  designation_id: number;
  grade_id: number | null;
  line_id: number | null;
  employee_group_id: number | null;
  shift_id: number | null;
  joining_date: string | null;
  previous_id_number: string | null;
  id_number: string;
  given_id_number: string;
  employee_full_id: string;
  name: string;
  bangla_name: string | null;
  phone_number: string | null;
  image: string;
  father_or_husband_name: string | null;
  mother_name: string | null;
  date_of_birth: string | null;
  gender: string;
  marital_status: string;
  religion: string | null;
  present_address: string | null;
  present_phone_number: string | null;
  permanent_address: string | null;
  permanent_phone_number: string | null;
  email: string | null;
  nationality: string | null;
  district: string | null;
  national_id: string | null;
  passport_no: string | null;
  employee_type: string;
  volunteer_type: string | null;
  p_bonus_type: string | null;
  device_id: string | null;
  finger_print_id: string | null;
  mfs_type: string | null;
  mfs: string | null;
  card_no: string | null;
  status: number;
  created_at: string;
  updated_at: string;
  over_time_status: number;
  signature: string | null;
  spouse_name: string | null;
  spouse_phone_number: string | null;
  employment_status: string | null;
  cv: string | null;
  hierarchy: number;
  employee_facility: string | null;
  designation_code: number;
  branch_id: number;
  zone_id: number | null;
  payer_category_id: number | null;
  payer_zone: string;
  probation_period: number;
  track_permission: number;
  attendance_area: string | null;
  employment_source: string | null;
  phone_no_1: string | null;
  phone_no_2: string | null;
  retirement_age: number | null;
  present_address_2: string | null;
  present_subdistrict: string | null;
  present_postal_code: string | null;
  present_lattitude: string | null;
  present_longitude: string | null;
  permanent_address_2: string | null;
  permanent_subdistrict: string | null;
  permanent_district: string | null;
  permanent_postal_code: string | null;
  permanent_lattitude: string | null;
  permanent_longitude: string | null;
  appointment_date: string | null;
  conformation_date: string | null;
  sepration_date: string | null;
  seperation_type: string | null;
  company: {
    id: number;
    group_id: number;
    business_type_id: number | null;
    name: string;
    code: string;
    is_mother_company: boolean | null;
    short_name: string;
    head_office: string;
    factory: string;
    contact_name: string;
    position: string;
    phone_number: string;
    fax: string;
    email: string;
    day_off: string;
    starting_month: string;
    country: string;
    top_text: string;
    logo: string;
    created_at: string;
    updated_at: string;
    latitude: string;
    longitude: string;
    business_type: string;
    status: number;
    group: {
      id: number;
      name: string;
      email: string;
      phone: string;
      address: string;
      logo: string;
      created_at: string;
      updated_at: string;
      fav_icon: string | null;
      login_background_image: string | null;
    };
  };
  department: {
    id: number;
    created_by: number;
    updated_by: number;
    group_id: number;
    company_id: number;
    name: string;
    code: string;
    created_at: string;
    updated_at: string;
  };
  designation: {
    id: number;
    created_by: number;
    updated_by: number;
    group_id: number;
    company_id: number;
    org_structure_id: number;
    name: string;
    code: string;
    created_at: string;
    updated_at: string;
    parent_id: number | null;
  };
  grade: string | null;
  educational_qualification: any[]; // Adjust type if structure is known
  experience: {
    id: number;
    created_by: number;
    updated_by: number;
    company_id: number;
    employee_id: number;
    company_name: string;
    designation: string;
    duration: string | null;
    file: string;
    created_at: string;
    updated_at: string;
    job_title: string | null;
    reference: string | null;
  }[];
  personal_information: any | null; // Adjust type if structure is known
  guardian: any | null; // Adjust type if structure is known
  reference_person: any | null; // Adjust type if structure is known
  bank_informations: any[]; // Adjust type if structure is known
  emp_assign_org: {
    id: number;
    company_id: number;
    employee_id: number;
    designation_id: number;
    business_unit_id: number;
    sales_line_id: number;
    zone_id: number;
    region_id: number;
    area_id: number;
    territory_id: number;
    start_date: string;
    end_date: string;
    created_at: string;
    updated_at: string;
  };
};
